# Generated by GitHub Copilot
"""
鼠标点击录制与循环回放工具

使用方法：
  录制模式：python mouse_recorder.py record
  回放模式：python mouse_recorder.py play [循环次数]  (默认无限循环，Ctrl+C 停止)

录制时按 Esc 键停止录制，结果保存至 mouse_record.json
"""

import argparse
import json
import sys
import time
from pathlib import Path

RECORD_FILE = Path(__file__).parent / "mouse_record.json"


# ──────────────────────────────────────────────
# 录制
# ──────────────────────────────────────────────
def record():
    """监听鼠标左键单击事件，记录坐标与时间戳，按 Esc 停止。"""
    try:
        from pynput import keyboard, mouse
    except ImportError:
        sys.exit("请先安装依赖：pip install pynput")

    events: list[dict] = []
    start_time: float | None = None
    stop_flag = {"value": False}

    def on_click(x, y, button, pressed):
        nonlocal start_time
        if not pressed or button != mouse.Button.left:
            return
        now = time.time()
        if start_time is None:
            start_time = now
        delay = round(now - start_time, 4)
        start_time = now
        events.append({"x": x, "y": y, "delay": delay})
        print(f"  [记录] ({x:>5}, {y:>5})  延迟 {delay:.3f}s")

    def on_key(key):
        if key == keyboard.Key.esc:
            stop_flag["value"] = True
            return False  # 停止监听

    print("=== 录制模式 ===")
    print("请开始点击鼠标左键。按 Esc 键停止录制。\n")

    mouse_listener = mouse.Listener(on_click=on_click)
    key_listener = keyboard.Listener(on_press=on_key)

    mouse_listener.start()
    key_listener.start()
    key_listener.join()          # 阻塞直到 Esc
    mouse_listener.stop()

    if not events:
        print("\n未录制到任何点击，退出。")
        return

    # 第一个事件延迟无意义，设为 0
    events[0]["delay"] = 0.0

    RECORD_FILE.write_text(json.dumps(events, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n✅ 录制完成，共 {len(events)} 个点击，已保存至 {RECORD_FILE}")


# ──────────────────────────────────────────────
# 回放
# ──────────────────────────────────────────────
def play(loops: int = 0):
    """按录制的坐标与时间间隔循环回放点击。loops=0 表示无限循环。"""
    try:
        import pyautogui
    except ImportError:
        sys.exit("请先安装依赖：pip install pyautogui")

    if not RECORD_FILE.exists():
        sys.exit(f"找不到录制文件：{RECORD_FILE}\n请先运行录制模式。")

    events: list[dict] = json.loads(RECORD_FILE.read_text(encoding="utf-8"))
    if not events:
        sys.exit("录制文件为空，请重新录制。")

    # 安全设置：将鼠标移到屏幕左上角可触发 failsafe 停止
    pyautogui.FAILSAFE = True
    pyautogui.PAUSE = 0  # 关闭 pyautogui 自带延迟，由我们手动控制

    loop_label = "∞" if loops == 0 else str(loops)
    print(f"=== 回放模式 ===  共 {len(events)} 个点击，循环 {loop_label} 次")
    print("将鼠标移到屏幕左上角 (0,0) 可紧急停止。\n")

    # 回放前等待 2 秒，留出切换窗口的时间
    for i in range(2, 0, -1):
        print(f"  {i} 秒后开始...", end="\r")
        time.sleep(1)
    print("  开始回放！             ")

    round_num = 0
    try:
        while True:
            round_num += 1
            print(f"\n── 第 {round_num} 轮 {'/' + str(loops) if loops else ''} ──")
            for idx, ev in enumerate(events):
                time.sleep(ev["delay"])
                pyautogui.click(ev["x"], ev["y"])
                print(f"  [点击 {idx+1:>2}] ({ev['x']:>5}, {ev['y']:>5})")

            if loops and round_num >= loops:
                break

    except KeyboardInterrupt:
        print("\n\n⏹ 用户中断回放。")
    except pyautogui.FailSafeException:
        print("\n\n🛑 检测到 Failsafe（鼠标移至左上角），回放已停止。")

    print(f"\n✅ 回放结束，共完成 {round_num} 轮。")


# ──────────────────────────────────────────────
# 入口
# ──────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="鼠标点击录制与循环回放工具")
    sub = parser.add_subparsers(dest="cmd")

    sub.add_parser("record", help="录制鼠标点击（按 Esc 停止）")

    p_play = sub.add_parser("play", help="回放录制的点击")
    p_play.add_argument(
        "loops",
        nargs="?",
        type=int,
        default=0,
        help="循环次数（默认 0 = 无限循环）",
    )

    # ATR 平台自动附加的认证参数，忽略即可
    parser.add_argument("-b", "--atr_url",  required=False, help=argparse.SUPPRESS)
    parser.add_argument("-a", "--atr_user", required=False, help=argparse.SUPPRESS)
    parser.add_argument("-p", "--atr_pass", required=False, help=argparse.SUPPRESS)

    args = parser.parse_args()

    if args.cmd == "record":
        record()
    elif args.cmd == "play":
        play(args.loops)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
