# Generated by GitHub Copilot
"""
谷子代购打表排发自助管理系统（双角色密码版）
- 买家：直接访问，只能看「买家查询」
- 管理员：侧边栏输入密码后解锁全部功能
运行命令：streamlit run 谷子代购管理系统.py
修改密码：将 ADMIN_PASSWORD_HASH 替换为新密码的 SHA-256 哈希值
"""

import hashlib
import hmac
import streamlit as st
import pandas as pd
import os
import uuid
from datetime import datetime
from io import BytesIO

# ── 常量配置 ──────────────────────────────────────────────────────────────────

DATA_FILE = os.path.join(os.path.dirname(__file__), "orders_data.xlsx")

# 密码哈希：当前密码为 admin123
# 修改密码方法：python -c "import hashlib; print(hashlib.sha256('新密码'.encode()).hexdigest())"
ADMIN_PASSWORD_HASH = hashlib.sha256("admin123".encode()).hexdigest()

COLUMNS = [
    "订单号", "买家昵称", "商品名称", "款式规格",
    "数量", "单价(元)", "总价(元)",
    "付款状态", "批次", "发货状态", "备注", "录入时间",
]

PAY_STATUS_OPTIONS  = ["未付款", "已付定金", "已付全款", "尾款待付"]
SHIP_STATUS_OPTIONS = ["已下单", "收肾中", "可排发", "已出荷"]


# ── 数据层 ────────────────────────────────────────────────────────────────────

def load_data() -> pd.DataFrame:
    """从 Excel 加载全量订单数据，文件不存在时返回空表。"""
    if os.path.exists(DATA_FILE):
        try:
            df = pd.read_excel(DATA_FILE, dtype=str)
            # 补全缺少的列，防止旧版本文件结构不匹配
            for col in COLUMNS:
                if col not in df.columns:
                    df[col] = ""
            return df[COLUMNS]
        except Exception:
            st.error("数据文件损坏，已重置为空表。")
    return pd.DataFrame(columns=COLUMNS)


def save_data(df: pd.DataFrame) -> None:
    """将 DataFrame 保存到 Excel。"""
    df.to_excel(DATA_FILE, index=False)


def generate_order_id() -> str:
    """生成唯一订单号，格式：ORD-YYYYMMDD-XXXXXX"""
    date_str  = datetime.now().strftime("%Y%m%d")
    short_uid = str(uuid.uuid4())[:6].upper()
    return f"ORD-{date_str}-{short_uid}"


def df_to_excel_bytes(df: pd.DataFrame) -> bytes:
    """将 DataFrame 导出为内存中的 Excel 文件字节流。"""
    buf = BytesIO()
    with pd.ExcelWriter(buf, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="Sheet1")
    return buf.getvalue()


def check_password(raw: str) -> bool:
    """对比输入密码与存储哈希，使用恒定时间比较防止时序攻击。"""
    return hmac.compare_digest(
        hashlib.sha256(raw.encode()).hexdigest(),
        ADMIN_PASSWORD_HASH,
    )


# ── 侧边栏：身份验证 ──────────────────────────────────────────────────────────

def sidebar_auth() -> bool:
    """
    渲染侧边栏登录区，返回是否为管理员。
    密码正确后状态存入 session_state，刷新页面不需重新输入。
    """
    with st.sidebar:
        st.title("🔐 管理员登录")
        if st.session_state.get("is_admin"):
            st.success("✅ 已登录为管理员")
            if st.button("退出登录", use_container_width=True):
                st.session_state.is_admin = False
                st.rerun()
            return True

        pwd = st.text_input("请输入管理员密码", type="password", key="pwd_input")
        if st.button("登录", use_container_width=True):
            if check_password(pwd):
                st.session_state.is_admin = True
                st.rerun()
            else:
                st.error("密码错误")

        st.divider()
        st.caption("买家无需登录，直接在右侧查询即可。")
        return False


# ── 页面：录入订单（仅管理员） ────────────────────────────────────────────────

def page_input(df: pd.DataFrame) -> pd.DataFrame:
    st.header("📋 录入订单")

    with st.form("order_form", clear_on_submit=True):
        col1, col2 = st.columns(2)
        with col1:
            nickname   = st.text_input("买家昵称 *")
            item_name  = st.text_input("商品名称 *")
            item_spec  = st.text_input("款式 / 规格（如：A款-白）")
            qty        = st.number_input("数量", min_value=1, value=1, step=1)
        with col2:
            unit_price = st.number_input("单价（元）", min_value=0.0, value=0.0, step=0.5, format="%.2f")
            pay_status = st.selectbox("付款状态", PAY_STATUS_OPTIONS)
            batch      = st.text_input("批次（如：第1批）", value="第1批")
            note       = st.text_input("备注")

        submitted = st.form_submit_button("✅ 提交订单", use_container_width=True)

    if submitted:
        if not nickname.strip() or not item_name.strip():
            st.warning("买家昵称和商品名称为必填项。")
            return df

        total_price = round(float(qty) * unit_price, 2)
        new_row = {
            "订单号":    generate_order_id(),
            "买家昵称":  nickname.strip(),
            "商品名称":  item_name.strip(),
            "款式规格":  item_spec.strip(),
            "数量":      str(qty),
            "单价(元)":  str(unit_price),
            "总价(元)":  str(total_price),
            "付款状态":  pay_status,
            "批次":      batch.strip(),
            "发货状态":  "待发货",
            "备注":      note.strip(),
            "录入时间":  datetime.now().strftime("%Y-%m-%d %H:%M"),
        }
        df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
        save_data(df)
        st.success(f"✅ 订单已录入！订单号：{new_row['订单号']}")

    return df


# ── 页面：管理总表（管理员） ─────────────────────────────────────────────────

def page_admin(df: pd.DataFrame) -> pd.DataFrame:
    st.header("🗂 订单总表（管理员）")

    if df.empty:
        st.info("暂无订单数据。")
        return df

    # 筛选栏
    col1, col2, col3 = st.columns(3)
    with col1:
        filter_batch    = st.selectbox("按批次筛选", ["全部"] + sorted(df["批次"].dropna().unique().tolist()))
    with col2:
        filter_pay      = st.selectbox("付款状态", ["全部"] + PAY_STATUS_OPTIONS)
    with col3:
        filter_ship     = st.selectbox("发货状态", ["全部"] + SHIP_STATUS_OPTIONS)

    view = df.copy()
    if filter_batch != "全部":
        view = view[view["批次"] == filter_batch]
    if filter_pay != "全部":
        view = view[view["付款状态"] == filter_pay]
    if filter_ship != "全部":
        view = view[view["发货状态"] == filter_ship]

    st.caption(f"共 {len(view)} 条订单")

    # 可编辑表格（更新付款/发货状态）
    edited = st.data_editor(
        view,
        column_config={
            "付款状态": st.column_config.SelectboxColumn(options=PAY_STATUS_OPTIONS),
            "发货状态": st.column_config.SelectboxColumn(options=SHIP_STATUS_OPTIONS),
        },
        use_container_width=True,
        num_rows="fixed",
        key="admin_table",
    )

    col_save, col_del, col_export = st.columns(3)

    with col_save:
        if st.button("💾 保存更改", use_container_width=True):
            # 将编辑后的行覆盖回原始 DataFrame
            df.update(edited)
            save_data(df)
            st.success("已保存。")

    with col_del:
        del_id = st.text_input("输入要删除的订单号", key="del_input", label_visibility="collapsed",
                               placeholder="输入订单号后点删除")
        if st.button("🗑 删除该订单", use_container_width=True):
            if del_id.strip() in df["订单号"].values:
                df = df[df["订单号"] != del_id.strip()].reset_index(drop=True)
                save_data(df)
                st.success(f"已删除订单 {del_id.strip()}")
                st.rerun()
            else:
                st.warning("未找到该订单号。")

    with col_export:
        st.download_button(
            label="📥 导出当前视图 Excel",
            data=df_to_excel_bytes(view),
            file_name=f"订单表_{datetime.now().strftime('%Y%m%d_%H%M')}.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            use_container_width=True,
        )

    return df


# ── 页面：买家自助查询 ───────────────────────────────────────────────────────

def page_query(df: pd.DataFrame) -> None:
    st.header("🔍 自助查询我的订单")
    st.caption("输入你的买家昵称或订单号，查看当前状态。")

    keyword = st.text_input("买家昵称 或 订单号", placeholder="如：小白兔 或 ORD-20260605-XXXX")

    if keyword.strip():
        kw = keyword.strip()
        result = df[
            df["买家昵称"].str.contains(kw, case=False, na=False) |
            df["订单号"].str.upper().str.contains(kw.upper(), na=False)
        ]

        if result.empty:
            st.warning("😢 没有找到相关订单，请确认昵称/订单号是否正确。")
        else:
            SHOW_COLS = ["订单号", "商品名称", "款式规格", "数量", "总价(元)", "付款状态", "批次", "发货状态", "备注"]
            st.success(f"找到 {len(result)} 条订单：")
            st.dataframe(result[SHOW_COLS], use_container_width=True, hide_index=True)

    st.divider()
    st.markdown(
        "**付款状态说明：**\n"
        "- 未付款 → 需完成付款\n"
        "- 已付定金 → 尾款开票后通知\n"
        "- 已付全款 → 等待发货\n"
        "- 尾款待付 → 请尽快补尾款\n\n"
        "**发货状态说明：**\n"
        "- 待发货 → 货物未出\n"
        "- 已发货 → 请查收快递通知\n"
        "- 已签收 → 完成 🎉"
    )


# ── 页面：排发清单 ───────────────────────────────────────────────────────────

def page_dispatch(df: pd.DataFrame) -> None:
    st.header("🚚 排发清单")

    if df.empty:
        st.info("暂无订单数据。")
        return

    batches = sorted(df["批次"].dropna().unique().tolist())
    if not batches:
        st.info("尚未设置批次。")
        return

    selected_batch = st.selectbox("选择发货批次", batches)
    batch_df = df[df["批次"] == selected_batch].copy()

    # 统计卡片
    total_orders  = len(batch_df)
    paid_orders   = len(batch_df[batch_df["付款状态"] == "已付全款"])
    unpaid_orders = total_orders - paid_orders

    c1, c2, c3 = st.columns(3)
    c1.metric("本批订单总数", total_orders)
    c2.metric("已付全款",     paid_orders)
    c3.metric("未全款（待确认）", unpaid_orders, delta_color="inverse")

    st.divider()

    # 按商品汇总表（用于备货核查）
    st.subheader("📦 商品备货汇总")
    summary = (
        batch_df.groupby(["商品名称", "款式规格"])
        .agg(总数量=("数量", lambda x: sum(pd.to_numeric(x, errors="coerce").fillna(0)))  )
        .reset_index()
    )
    st.dataframe(summary, use_container_width=True, hide_index=True)

    st.divider()

    # 逐单发货明细
    st.subheader("📋 逐单发货明细")
    DISPATCH_COLS = ["订单号", "买家昵称", "商品名称", "款式规格", "数量", "付款状态", "发货状态", "备注"]
    st.dataframe(batch_df[DISPATCH_COLS], use_container_width=True, hide_index=True)

    # 导出发货单
    st.download_button(
        label=f"📥 导出「{selected_batch}」发货单 Excel",
        data=df_to_excel_bytes(batch_df[DISPATCH_COLS]),
        file_name=f"排发单_{selected_batch}_{datetime.now().strftime('%Y%m%d')}.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        use_container_width=True,
    )


# ── 主入口 ────────────────────────────────────────────────────────────────────

def main() -> None:
    st.set_page_config(
        page_title="自助查询排发系统",
        page_icon="🎁",
        layout="wide",
    )

    # 统一中文字体，消除粗细不一的问题
    st.markdown(
        """
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;600&display=swap');

        * {
            font-family: "Noto Sans SC", "PingFang SC", "Microsoft YaHei",
                         "Source Han Sans CN", sans-serif !important;
        }
        h1, h2, h3, h4, h5, h6,
        .stHeading, [data-testid="stHeadingWithActionElements"],
        [data-testid="stHeadingWithActionElements"] * {
            font-weight: 600 !important;
        }
        p, span, div, label, button,
        .stMarkdown, .stCaption, .stText {
            font-weight: 400 !important;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )

    st.title("🎁 自助查询排发系统")

    is_admin = sidebar_auth()

    if "df" not in st.session_state:
        st.session_state.df = load_data()

    if is_admin:
        # 管理员：全部 4 个 Tab
        st.caption("当前身份：**管理员**")
        tabs = st.tabs(["📋 录入订单", "🗂 订单总表", "🔍 买家查询", "🚚 排发清单"])
        with tabs[0]:
            st.session_state.df = page_input(st.session_state.df)
        with tabs[1]:
            st.session_state.df = page_admin(st.session_state.df)
        with tabs[2]:
            page_query(st.session_state.df)
        with tabs[3]:
            page_dispatch(st.session_state.df)
    else:
        # 买家：仅查询
        st.caption("买家视图 · 如需管理请在左侧登录")
        page_query(st.session_state.df)


if __name__ == "__main__":
    main()
