# Generated by GitHub Copilot
"""
谷子代购打表排发自助管理系统（双角色密码版）
- 买家：直接访问，只能看「买家查询」
- 管理员：侧边栏输入密码后解锁全部功能
运行命令：streamlit run 谷子代购管理系统.py
修改密码：将 ADMIN_PASSWORD_HASH 替换为新密码的 SHA-256 哈希值
"""

import hashlib
import hmac
import streamlit as st
import streamlit.components.v1
import pandas as pd
import os
import uuid
from datetime import datetime
from io import BytesIO

# ── 常量配置 ──────────────────────────────────────────────────────────────────

DATA_FILE = os.path.join(os.path.dirname(__file__), "orders_data.xlsx")
IMAGE_DIR = os.path.join(os.path.dirname(__file__), "order_images")

# 密码哈希：当前密码为 admin123
# 修改密码方法：python -c "import hashlib; print(hashlib.sha256('新密码'.encode()).hexdigest())"
ADMIN_PASSWORD_HASH = hashlib.sha256("admin123".encode()).hexdigest()

COLUMNS = [
    "订单号", "买家昵称", "商品名称", "款式规格",
    "数量", "单价(元)", "总价(元)",
    "付款状态", "发货状态", "备注", "录入时间", "图片",
]

PAY_STATUS_OPTIONS  = ["未付款", "已付定金", "已付全款", "尾款待付"]
SHIP_STATUS_OPTIONS = ["已下单", "收肾中", "可排发", "已出荷"]


# ── 数据层 ────────────────────────────────────────────────────────────────────

def load_data() -> pd.DataFrame:
    """从 Excel 加载全量订单数据，文件不存在时返回空表。"""
    if os.path.exists(DATA_FILE):
        try:
            df = pd.read_excel(DATA_FILE, dtype=str)
            # 补全缺少的列，防止旧版本文件结构不匹配
            for col in COLUMNS:
                if col not in df.columns:
                    df[col] = ""
            return df[COLUMNS]
        except Exception:
            st.error("数据文件损坏，已重置为空表。")
    return pd.DataFrame(columns=COLUMNS)


def save_data(df: pd.DataFrame) -> None:
    """将 DataFrame 保存到 Excel。"""
    df.to_excel(DATA_FILE, index=False)


def generate_order_id() -> str:
    """生成唯一订单号，格式：ORD-YYYYMMDD-XXXXXX"""
    date_str  = datetime.now().strftime("%Y%m%d")
    short_uid = str(uuid.uuid4())[:6].upper()
    return f"ORD-{date_str}-{short_uid}"


def df_to_excel_bytes(df: pd.DataFrame) -> bytes:
    """将 DataFrame 导出为内存中的 Excel 文件字节流。"""
    buf = BytesIO()
    with pd.ExcelWriter(buf, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="Sheet1")
    return buf.getvalue()


def check_password(raw: str) -> bool:
    """对比输入密码与存储哈希，使用恒定时间比较防止时序攻击。"""
    return hmac.compare_digest(
        hashlib.sha256(raw.encode()).hexdigest(),
        ADMIN_PASSWORD_HASH,
    )


@st.dialog("🖼 订单图片管理", width="large")
def image_dialog(order_id: str, buyer: str, item: str, df: pd.DataFrame) -> None:
    """弹出对话框：查看 / 上传 / 删除指定订单的图片。"""
    st.caption(f"订单号：{order_id}　买家：{buyer}　商品：{item}")
    imgs = list_order_images(order_id)

    if imgs:
        st.write(f"当前已有 **{len(imgs)}** 张图片")
        for i, img_path in enumerate(imgs):
            with st.expander(f"图片 {i+1}", expanded=False):
                    os.remove(img_path)
                    df.loc[df["订单号"] == order_id, "图片"] = image_count_label(order_id)
                    save_data(df)
                    st.rerun()
    else:
        st.info("该订单暂无图片")

    st.divider()
    uploaded = st.file_uploader(
        "上传新图片（支持 jpg / png / gif / webp，可多选）",
        type=["jpg", "jpeg", "png", "gif", "webp"],
        accept_multiple_files=True,
        key=f"dlg_upload_{order_id}",
    )
    if uploaded:
        if st.button("✅ 保存图片", key="dlg_img_save"):
            for f in uploaded:
                save_order_image(order_id, f)
            df.loc[df["订单号"] == order_id, "图片"] = image_count_label(order_id)
            save_data(df)
            st.success(f"已上传 {len(uploaded)} 张图片。")
            st.rerun()


def list_order_images(order_id: str) -> list:
    """返回该订单在 IMAGE_DIR 中所有图片的完整路径列表（按文件名排序）。"""
    if not os.path.isdir(IMAGE_DIR):
        return []
    prefix = order_id + "_"
    return sorted(
        os.path.join(IMAGE_DIR, f)
        for f in os.listdir(IMAGE_DIR)
        if f.startswith(prefix)
    )


def save_order_image(order_id: str, uploaded_file) -> str:
    """将上传的图片保存到 IMAGE_DIR，返回保存的完整路径。"""
    os.makedirs(IMAGE_DIR, exist_ok=True)
    existing = list_order_images(order_id)
    idx = len(existing) + 1
    ext = os.path.splitext(uploaded_file.name)[-1].lower() or ".jpg"
    # 限制扩展名，防止意外文件类型
    if ext not in (".jpg", ".jpeg", ".png", ".gif", ".webp"):
        ext = ".jpg"
    filename = f"{order_id}_{idx:03d}{ext}"
    dest = os.path.join(IMAGE_DIR, filename)
    with open(dest, "wb") as f:
        f.write(uploaded_file.getbuffer())
    return dest


def image_count_label(order_id: str) -> str:
    """返回订单图片数的显示文字，无图片时返回空字符串。"""
    n = len(list_order_images(order_id))
    return f"{n}张" if n else ""


# ── 侧边栏：身份验证 ──────────────────────────────────────────────────────────

def sidebar_auth() -> bool:
    """
    渲染侧边栏登录区，返回是否为管理员。
    密码正确后状态存入 session_state，刷新页面不需重新输入。
    """
    with st.sidebar:
        st.title("🔐 管理员登录")
        if st.session_state.get("is_admin"):
            st.success("✅ 已登录为管理员")
            if st.button("退出登录", use_container_width=True):
                st.session_state.is_admin = False
                st.rerun()
            return True

        pwd = st.text_input("请输入管理员密码", type="password", key="pwd_input")
        if st.button("登录", use_container_width=True):
            if check_password(pwd):
                st.session_state.is_admin = True
                st.rerun()
            else:
                st.error("密码错误")

        st.divider()
        st.caption("买家无需登录，直接在右侧查询即可。")
        return False


# ── 页面：录入订单（仅管理员） ────────────────────────────────────────────────

# Excel 批量导入的列（不含订单号、录入时间、图片，这三列自动填充）
IMPORT_COLUMNS = ["买家昵称", "商品名称", "款式规格", "数量", "单价(元)", "备注"]


def make_import_template() -> bytes:
    """生成空白导入模板 Excel（列顺序与 IMPORT_COLUMNS 一致）。"""
    tpl = pd.DataFrame(columns=IMPORT_COLUMNS)
    buf = BytesIO()
    with pd.ExcelWriter(buf, engine="openpyxl") as writer:
        tpl.to_excel(writer, index=False, sheet_name="导入模板")
    return buf.getvalue()


def page_input(df: pd.DataFrame) -> pd.DataFrame:
    st.header("📋 录入订单")

    tab_single, tab_bulk = st.tabs(["✏️ 逐条录入", "📂 Excel 批量导入"])

    # ── 逐条录入 ────────────────────────────────────────────────────────────
    with tab_single:
        with st.form("order_form", clear_on_submit=True):
            col1, col2 = st.columns(2)
            with col1:
                nickname   = st.text_input("买家昵称 *")
                item_name  = st.text_input("商品名称 *")
                item_spec  = st.text_input("款式 / 规格（如：A款-白）")
                qty        = st.number_input("数量", min_value=1, value=1, step=1)
            with col2:
                unit_price = st.number_input("单价（元）", min_value=0.0, value=0.0, step=0.5, format="%.2f")
                pay_status = st.selectbox("付款状态", PAY_STATUS_OPTIONS)
                note       = st.text_input("备注")

            submitted = st.form_submit_button("✅ 提交订单", use_container_width=True)

        if submitted:
            if not nickname.strip() or not item_name.strip():
                st.warning("买家昵称和商品名称为必填项。")
                return df

            total_price = round(float(qty) * unit_price, 2)
            new_row = {
                "订单号":    generate_order_id(),
                "买家昵称":  nickname.strip(),
                "商品名称":  item_name.strip(),
                "款式规格":  item_spec.strip(),
                "数量":      str(qty),
                "单价(元)":  str(unit_price),
                "总价(元)":  str(total_price),
                "付款状态":  pay_status,
                "发货状态":  "待发货",
                "备注":      note.strip(),
                "录入时间":  datetime.now().strftime("%Y-%m-%d %H:%M"),
                "图片":      "",
            }
            df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
            save_data(df)
            st.success(f"✅ 订单已录入！订单号：{new_row['订单号']}")

    # ── Excel 批量导入 ───────────────────────────────────────────────────────
    with tab_bulk:
        st.caption("请下载模板，按格式填写后上传。订单号与录入时间将自动生成，无需填写。")

        st.download_button(
            label="⬇️ 下载导入模板",
            data=make_import_template(),
            file_name="订单导入模板.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )

        uploaded_xl = st.file_uploader(
            "上传填好的 Excel 文件",
            type=["xlsx", "xls"],
            key="bulk_import_file",
        )

        if uploaded_xl:
            try:
                imp = pd.read_excel(uploaded_xl, dtype=str).fillna("")
            except Exception as e:
                st.error(f"文件读取失败：{e}")
                return df

            # 检查必要列
            missing = [c for c in ["买家昵称", "商品名称"] if c not in imp.columns]
            if missing:
                st.error(f"文件缺少必要列：{missing}，请使用下载的模板。")
                return df

            # 补全缺失的可选列
            for col in IMPORT_COLUMNS:
                if col not in imp.columns:
                    imp[col] = ""

            # 过滤空行（买家昵称或商品名称为空）
            imp = imp[imp["买家昵称"].str.strip().ne("") & imp["商品名称"].str.strip().ne("")]

            if imp.empty:
                st.warning("文件中没有有效数据行（买家昵称和商品名称不能为空）。")
                return df

            st.write(f"识别到 **{len(imp)}** 条有效数据，预览如下：")
            st.dataframe(imp[IMPORT_COLUMNS], use_container_width=True, hide_index=True)

            if st.button("✅ 确认导入", key="confirm_bulk_import", use_container_width=True):
                now = datetime.now().strftime("%Y-%m-%d %H:%M")
                new_rows = []
                for _, row in imp.iterrows():
                    new_rows.append({
                        "订单号":    generate_order_id(),
                        "买家昵称":  row.get("买家昵称", "").strip(),
                        "商品名称":  row.get("商品名称", "").strip(),
                        "款式规格":  row.get("款式规格", "").strip(),
                        "数量":      row.get("数量", "").strip(),
                        "单价(元)":  row.get("单价(元)", "").strip(),
                        "总价(元)":  "",
                        "付款状态":  PAY_STATUS_OPTIONS[0],
                        "发货状态":  "待发货",
                        "备注":      row.get("备注", "").strip(),
                        "录入时间":  now,
                        "图片":      "",
                    })
                df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
                save_data(df)
                st.success(f"✅ 已成功导入 {len(new_rows)} 条订单！")
                st.rerun()

    return df


# ── 页面：管理总表（管理员） ─────────────────────────────────────────────────

def page_admin(df: pd.DataFrame) -> pd.DataFrame:
    st.header("🗂 订单总表（管理员）")

    if df.empty:
        st.info("暂无订单数据。")
        return df

    # ── 筛选栏 ──────────────────────────────────────────────────────────────
    col1, col2, col3 = st.columns(3)
    with col1:
        filter_pay  = st.selectbox("付款状态", ["全部"] + PAY_STATUS_OPTIONS, key="adm_f_pay")
    with col2:
        filter_ship = st.selectbox("发货状态", ["全部"] + SHIP_STATUS_OPTIONS, key="adm_f_ship")
    with col3:
        filter_kw   = st.text_input("关键词", placeholder="买家昵称 / 商品名称", key="adm_f_kw")

    view = df.copy()
    if filter_pay != "全部":
        view = view[view["付款状态"] == filter_pay]
    if filter_ship != "全部":
        view = view[view["发货状态"] == filter_ship]
    if filter_kw.strip():
        kw = filter_kw.strip()
        view = view[
            view["买家昵称"].str.contains(kw, case=False, na=False) |
            view["商品名称"].str.contains(kw, case=False, na=False)
        ]

    st.caption(f"共 {len(view)} 条订单")

    # ── 可编辑表格 ──────────────────────────────────────────────────────────
    edited = st.data_editor(
        view,
        column_config={
            "付款状态": st.column_config.SelectboxColumn(options=PAY_STATUS_OPTIONS),
            "发货状态": st.column_config.SelectboxColumn(options=SHIP_STATUS_OPTIONS),
            "总价(元)": st.column_config.TextColumn("总价(元)", disabled=True),
            "图片": st.column_config.TextColumn("📎 图片", disabled=True),
        },
        use_container_width=True,
        num_rows="fixed",
        key="adm_tbl",
    )

    # ── 图片操作条（紧贴表格，视觉上对应最右侧图片列） ──────────────────────
    if not view.empty:
        order_options = {
            oid: f"{buyer}　{item}" + (f"　[{image_count_label(oid)}]" if image_count_label(oid) else "")
            for oid, buyer, item in zip(
                view["订单号"], view["买家昵称"], view["商品名称"]
            )
        }
        ic1, ic2 = st.columns([5, 1])
        with ic1:
            sel_oid = st.selectbox(
                "选择要管理图片的订单",
                options=list(order_options.keys()),
                format_func=lambda k: order_options[k],
                label_visibility="collapsed",
                key="adm_img_sel",
            )
        with ic2:
            if st.button("📎 管理图片", key="adm_img_open", use_container_width=True):
                row = df[df["订单号"] == sel_oid].iloc[0]
                image_dialog(sel_oid, row["买家昵称"], row["商品名称"], df)

    # ── 保存行内编辑 & 导出 ─────────────────────────────────────────────────
    col_save, col_export = st.columns(2)
    with col_save:
        if st.button("💾 保存行内编辑", use_container_width=True):
            df.update(edited)
            # 根据数量和单价重算总价
            qty_num   = pd.to_numeric(df["数量"],    errors="coerce").fillna(0)
            price_num = pd.to_numeric(df["单价(元)"], errors="coerce").fillna(0)
            df["总价(元)"] = (qty_num * price_num).round(2).astype(str)
            save_data(df)
            st.success("已保存。")
            st.rerun()
    with col_export:
        st.download_button(
            label="📥 导出当前视图 Excel",
            data=df_to_excel_bytes(view),
            file_name=f"订单表_{datetime.now().strftime('%Y%m%d_%H%M')}.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            use_container_width=True,
        )

    st.divider()

    # ── 单条删除 ────────────────────────────────────────────────────────────
    with st.expander("🗑 按订单号删除单条"):
        del_id = st.text_input("订单号", key="del_input", placeholder="输入订单号后点删除")
        if st.button("删除该订单", key="del_single"):
            if del_id.strip() in df["订单号"].values:
                df = df[df["订单号"] != del_id.strip()].reset_index(drop=True)
                save_data(df)
                st.success(f"已删除订单 {del_id.strip()}")
                st.rerun()
            else:
                st.warning("未找到该订单号。")

    return df


# ── 页面：批量操作（管理员） ─────────────────────────────────────────────────

def page_batch(df: pd.DataFrame) -> pd.DataFrame:
    st.header("⚡ 批量操作")
    st.caption("先用筛选条件缩小范围，再全选或逐条勾选，最后执行批量动作。")

    if df.empty:
        st.info("暂无订单数据。")
        return df

    # ── 筛选栏 ──────────────────────────────────────────────────────────────
    col1, col2, col3 = st.columns(3)
    with col1:
        bp_pay  = st.selectbox("付款状态", ["全部"] + PAY_STATUS_OPTIONS, key="bp_f_pay")
    with col2:
        bp_ship = st.selectbox("发货状态", ["全部"] + SHIP_STATUS_OPTIONS, key="bp_f_ship")
    with col3:
        bp_kw   = st.text_input("关键词", placeholder="买家昵称 / 商品名称", key="bp_f_kw")

    view = df.copy()
    if bp_pay != "全部":
        view = view[view["付款状态"] == bp_pay]
    if bp_ship != "全部":
        view = view[view["发货状态"] == bp_ship]
    if bp_kw.strip():
        kw = bp_kw.strip()
        view = view[
            view["买家昵称"].str.contains(kw, case=False, na=False) |
            view["商品名称"].str.contains(kw, case=False, na=False)
        ]

    st.caption(f"筛选结果：{len(view)} 条")

    # ── Session state 初始化 ────────────────────────────────────────────────
    if "bp_ver" not in st.session_state:
        st.session_state.bp_ver    = 0
    if "bp_presel" not in st.session_state:
        st.session_state.bp_presel = False
    if "bp_fsig" not in st.session_state:
        st.session_state.bp_fsig   = None

    # 筛选条件变化时重置表格
    fsig = (bp_pay, bp_ship, bp_kw.strip())
    if st.session_state.bp_fsig != fsig:
        st.session_state.bp_fsig   = fsig
        st.session_state.bp_presel = False
        st.session_state.bp_ver   += 1

    # ── 全选 / 取消全选 ──────────────────────────────────────────────────────
    c_all, c_none, c_cnt = st.columns([1, 1, 4])
    with c_all:
        if st.button("☑ 全选筛选结果", use_container_width=True, key="bp_selall"):
            st.session_state.bp_presel = True
            st.session_state.bp_ver   += 1
            st.rerun()
    with c_none:
        if st.button("☐ 取消全选", use_container_width=True, key="bp_selnone"):
            st.session_state.bp_presel = False
            st.session_state.bp_ver   += 1
            st.rerun()

    # ── 带复选框的只读表格 ───────────────────────────────────────────────────
    view_sel = view.copy()
    view_sel.insert(0, "选择", bool(st.session_state.bp_presel))

    checked = st.data_editor(
        view_sel,
        column_config={
            "选择": st.column_config.CheckboxColumn("✓", default=False),
        },
        disabled=[c for c in view_sel.columns if c != "选择"],
        use_container_width=True,
        num_rows="fixed",
        key=f"bp_tbl_{st.session_state.bp_ver}",
    )

    if st.session_state.bp_presel:
        st.session_state.bp_presel = False

    selected_ids = checked[checked["选择"] == True]["订单号"].tolist()
    c_cnt.caption(f"已选中 **{len(selected_ids)}** 条")

    st.divider()

    # ── 批量操作区 ───────────────────────────────────────────────────────────
    st.subheader("执行批量操作")
    if not selected_ids:
        st.info("请先勾选订单。")
        return df

    st.caption(f"将对已选中的 **{len(selected_ids)}** 条订单执行以下操作")
    bc1, bc2, bc3 = st.columns(3)

    with bc1:
        bulk_pay = st.selectbox("批量设置付款状态", ["（不修改）"] + PAY_STATUS_OPTIONS, key="bp_bulk_pay")
        if st.button("✅ 应用付款状态", key="bp_apply_pay", use_container_width=True):
            if bulk_pay != "（不修改）":
                df.loc[df["订单号"].isin(selected_ids), "付款状态"] = bulk_pay
                save_data(df)
                st.success(f"已将 {len(selected_ids)} 条订单付款状态更新为「{bulk_pay}」")
                st.session_state.bp_ver += 1
                st.rerun()

    with bc2:
        bulk_ship = st.selectbox("批量设置发货状态", ["（不修改）"] + SHIP_STATUS_OPTIONS, key="bp_bulk_ship")
        if st.button("✅ 应用发货状态", key="bp_apply_ship", use_container_width=True):
            if bulk_ship != "（不修改）":
                df.loc[df["订单号"].isin(selected_ids), "发货状态"] = bulk_ship
                save_data(df)
                st.success(f"已将 {len(selected_ids)} 条订单发货状态更新为「{bulk_ship}」")
                st.session_state.bp_ver += 1
                st.rerun()

    with bc3:
        st.markdown("**批量删除**")
        if st.button(
            f"🗑 删除已选 {len(selected_ids)} 条",
            key="bp_bulk_del",
            use_container_width=True,
            type="primary",
        ):
            df = df[~df["订单号"].isin(selected_ids)].reset_index(drop=True)
            save_data(df)
            st.success(f"已删除 {len(selected_ids)} 条订单。")
            st.session_state.bp_ver += 1
            st.rerun()

    return df


# ── 页面：买家自助查询 ───────────────────────────────────────────────────────

def page_query(df: pd.DataFrame) -> None:
    st.header("🔍 自助查询我的订单")
    st.caption("输入你的买家昵称或订单号，查看当前状态。")

    keyword = st.text_input("买家昵称 或 订单号", placeholder="如：小白兔 或 ORD-20260605-XXXX")

    if keyword.strip():
        kw = keyword.strip()
        result = df[
            df["买家昵称"].str.contains(kw, case=False, na=False) |
            df["订单号"].str.upper().str.contains(kw.upper(), na=False)
        ]

        if result.empty:
            st.warning("😢 没有找到相关订单，请确认昵称/订单号是否正确。")
        else:
            SHOW_COLS = ["订单号", "商品名称", "款式规格", "数量", "总价(元)", "付款状态", "发货状态", "备注"]
            st.success(f"找到 {len(result)} 条订单：")
            st.dataframe(result[SHOW_COLS], use_container_width=True, hide_index=True)

            # 展示各订单图片
            for _, row in result.iterrows():
                imgs = list_order_images(row["订单号"])
                if imgs:
                    with st.expander(f"🖼 {row['订单号']} — {row['商品名称']}  图片（{len(imgs)}张）"):
                        for i, img_path in enumerate(imgs):
                            with st.expander(f"图片 {i+1}", expanded=False):
                                st.image(img_path, use_container_width=True)

    st.divider()
    st.markdown(
        "**付款状态说明：**\n"
        "- 未付款 → 需完成付款\n"
        "- 已付定金 → 尾款开票后通知\n"
        "- 已付全款 → 等待发货\n"
        "- 尾款待付 → 请尽快补尾款\n\n"
        "**发货状态说明：**\n"
        "- 待发货 → 货物未出\n"
        "- 已发货 → 请查收快递通知\n"
        "- 已签收 → 完成 🎉"
    )


# ── 主入口 ────────────────────────────────────────────────────────────────────

def main() -> None:
    st.set_page_config(
        page_title="自助查询排发系统",
        page_icon="🎁",
        layout="wide",
    )

    # 统一中文字体，消除粗细不一的问题
    st.markdown(
        """
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;600&display=swap');

        body, p, div, label, input, textarea, select,
        .stMarkdown, .stCaption, .stText, .stHeading,
        [data-testid="stHeadingWithActionElements"],
        [data-testid="stHeadingWithActionElements"] * {
            font-family: "Noto Sans SC", "PingFang SC", "Microsoft YaHei",
                         "Source Han Sans CN", sans-serif !important;
        }
        h1, h2, h3, h4, h5, h6,
        .stHeading, [data-testid="stHeadingWithActionElements"],
        [data-testid="stHeadingWithActionElements"] * {
            font-weight: 600 !important;
        }
        p, div, label,
        .stMarkdown, .stCaption, .stText {
            font-weight: 400 !important;
        }
        /* 恢复 Streamlit 图标字体，防止图标名称以文字显示 */
        span[class*="material-symbols"] {
            font-family: "Material Symbols Rounded", "Material Symbols Sharp",
                         "Material Symbols Outlined" !important;
        }
        /* 侧边栏折叠按钮：隐藏图标，显示「管理员入口」文字 */
        [data-testid="collapsedControl"] button span,
        [data-testid="stSidebarCollapsedControl"] button span {
            display: none !important;
        }
        [data-testid="collapsedControl"] button::after,
        [data-testid="stSidebarCollapsedControl"] button::after {
            content: "管理员入口";
            font-family: "Noto Sans SC", "PingFang SC", "Microsoft YaHei", sans-serif !important;
            font-size: 12px;
            font-weight: 600;
            writing-mode: vertical-rl;
            letter-spacing: 3px;
            color: #555;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )

    # JS 兜底：直接找到侧边栏折叠按钮，替换其文字内容
    st.components.v1.html(
        """
        <script>
        function patchSidebarBtn() {
            const btns = parent.document.querySelectorAll(
                '[data-testid="collapsedControl"] button, [data-testid="stSidebarCollapsedControl"] button'
            );
            btns.forEach(btn => {
                const span = btn.querySelector('span');
                if (span) { span.textContent = ''; span.style.display = 'none'; }
                if (!btn.dataset.patched) {
                    btn.dataset.patched = '1';
                    const label = document.createElement('span');
                    label.textContent = '管理员入口';
                    label.style.cssText = 'font-size:12px;writing-mode:vertical-rl;letter-spacing:3px;color:#555;font-weight:600;';
                    btn.appendChild(label);
                }
            });
        }
        // 页面加载后 + 1 秒后各执行一次，确保 Streamlit 渲染完毕
        patchSidebarBtn();
        setTimeout(patchSidebarBtn, 1000);
        </script>
        """,
        height=0,
    )

    st.title("🎁 自助查询排发系统")

    is_admin = sidebar_auth()

    if "df" not in st.session_state:
        st.session_state.df = load_data()

    if is_admin:
        # 管理员：全部 4 个 Tab
        st.caption("当前身份：**管理员**")
        tabs = st.tabs(["📋 录入订单", "🗂 订单总表", "⚡ 批量操作", "🔍 买家查询"])
        with tabs[0]:
            st.session_state.df = page_input(st.session_state.df)
        with tabs[1]:
            st.session_state.df = page_admin(st.session_state.df)
        with tabs[2]:
            st.session_state.df = page_batch(st.session_state.df)
        with tabs[3]:
            page_query(st.session_state.df)
    else:
        # 买家：仅查询
        st.caption("买家视图 · 如需管理请在左侧登录")
        page_query(st.session_state.df)


if __name__ == "__main__":
    main()
